apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: touchless-pipeline # executable id, must be unique across all your workflows (YAML files)
  annotations:
    scenarios.ai.sap.com/description: "Ingest Data for Touchless Recommendation"
    scenarios.ai.sap.com/name: "Touchless (Recommendations)" # Scenario name should be the use case
    executables.ai.sap.com/description: "Train with legacy data"
    executables.ai.sap.com/name: "dartraining" # Executable name should describe the workflow in the use case
    artifacts.ai.sap.com/dardataset.kind: "dataset" # Helps in suggesting the kind of inputs that can be attached.
    artifacts.ai.sap.com/dardatamodel.kind: "model" # Helps in suggesting the kind of artifact that can be generated.
  labels:
    scenarios.ai.sap.com/id: "touchless-learning-datalines"
    ai.sap.com/version: "1.0"
spec:
  imagePullSecrets:
    - name: docker-rajatfjain216 # your docker registry secret
  entrypoint: mypipeline
  arguments:
    parameters: # placeholder for string like inputs
        - name: DT_MAX_DEPTH # identifier local to this workflow
  templates:
  - name: mypipeline
    steps:
    - - name: mypredictor
        template: mycodeblock1
  - name: mycodeblock1
    metadata:
        labels:
            ai.sap.com/resourcePlan: starter
    inputs:
      artifacts:  # placeholder for cloud storage attachements
        - name: dardataset # a name for the placeholder
          path: /app/data/ # where to copy in the Dataset in the Docker image
    outputs:
      artifacts:
        - name: dardatamodel # local identifier name to the workflow
          globalName: touchlessmodel # name of the artifact generated, and folder name when placed in S3, complete directory will be `../<executaion_id>/housemodel`. Also used above in annotation
          path: /app/model/ # from which folder in docker image (after running workflow step) copy contents to cloud storage
          archive:
            none:   # specify not to compress while uploading to cloud
              {}
    container:
      image: docker.io/rajatfjain216/touchless-recommendation:01 # Your docker image name
      command: ["/bin/sh", "-c"]
      env:
        - name: DT_MAX_DEPTH # name of the environment variable inside Docker container
          value: "{{workflow.parameters.DT_MAX_DEPTH}}" # will make it as variable later
      args:
        - "python /app/src/main.py"
